# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-06 06:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertatrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column=b'punto', srid=4326)),
                ('i', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('foto', models.CharField(blank=True, max_length=128, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('nombre_emergencia', models.CharField(blank=True, max_length=128, null=True)),
                ('nro_emergencia', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo_contacto', models.CharField(blank=True, choices=[(b'PADRE', b'Padre'), (b'MADRE', b'Madre'), (b'ESPOSO', b'Esposa(o)'), (b'ABUELO', b'Abuelo(a)'), (b'HIJO', b'Hijo(a)'), (b'PAREJA', b'Pareja'), (b'POLOLO', b'Pololo(a)')], max_length=128, null=True)),
                ('cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=512, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=512, null=True)),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('ON LINE', 'On Line'), ('MIXTO', 'Mixto')], max_length=128, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroNegocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('codigo', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fono', models.CharField(blank=True, max_length=128, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=256, null=True)),
                ('nota', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('rut', models.CharField(blank=True, max_length=128, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=512, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listacn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listaplantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listatrabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Posicionestrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, null=True)),
                ('fixtime', models.DateTimeField(db_column=b'fixTime')),
                ('valid', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('attributes', models.CharField(max_length=4096)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column=b'punto', srid=4326)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidop', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidom', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=128, null=True)),
                ('emergencia', models.IntegerField(blank=True, null=True)),
                ('tipo_contacto', models.CharField(blank=True, choices=[(b'PADRE', b'Padre'), (b'MADRE', b'Madre'), (b'ESPOSO', b'Esposa(o)'), (b'ABUELO', b'Abuelo(a)'), (b'HIJO', b'Hijo(a)'), (b'PAREJA', b'Pareja'), (b'POLOLO', b'Pololo(a)')], max_length=128, null=True)),
                ('rut', models.CharField(blank=True, max_length=128, null=True)),
                ('centroNegocios', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('rol', models.IntegerField(blank=True, null=True)),
                ('gps', models.IntegerField(blank=True, null=True)),
                ('supervisor', models.IntegerField(blank=True, null=True)),
                ('empresa', models.IntegerField(blank=True, null=True)),
                ('salud', models.IntegerField(blank=True, null=True)),
                ('estudios', models.IntegerField(blank=True, null=True)),
                ('capacitacion', models.IntegerField(blank=True, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=256, null=True)),
                ('nota2', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('ALERGIA', 'Alergia'), ('ENFERMEDAD', 'Enfermedad')], max_length=128, null=True)),
                ('detalle', models.CharField(blank=True, max_length=128, null=True)),
                ('observacion', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testzona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempozona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estid', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidop', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidom', models.CharField(blank=True, max_length=128, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo_contacto', models.CharField(blank=True, choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ESPOSO', 'Esposa(o)'), ('ABUELO', 'Abuelo(a)'), ('HIJO', 'Hijo(a)'), ('PAREJA', 'Pareja'), ('POLOLO', 'Pololo(a)')], max_length=128, null=True)),
                ('rut', models.CharField(blank=True, max_length=128, null=True)),
                ('cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=256, null=True)),
                ('nota2', models.CharField(blank=True, max_length=256, null=True)),
                ('qrtext', models.CharField(blank=True, max_length=256, null=True)),
                ('qrimg', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('last_z', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=4096, null=True)),
                ('certificado', models.ImageField(blank=True, null=True, upload_to='capacitacion/')),
                ('capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Capacitacion')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono_gps', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Devices')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=4096, null=True)),
                ('certificado', models.ImageField(blank=True, null=True, upload_to='estudios/')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Estudios')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('uso', models.CharField(blank=True, max_length=128, null=True)),
                ('zona', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Planta')),
                ('riesgo', models.ManyToManyField(blank=True, null=True, to='est.Riesgo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='capacitacion',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorCapacitacion', to='est.Capacitacion'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='centroNegocios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.CentroNegocios'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='emergencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Contacto'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Empresa'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estudios',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorEstudios', to='est.Estudios'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='gps',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorDevice', to='gps.Devices'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rol',
            field=models.ManyToManyField(blank=True, null=True, to='est.Rol'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='salud',
            field=models.ManyToManyField(blank=True, null=True, to='est.Salud'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador'),
        ),
        migrations.AddField(
            model_name='rol',
            name='zonas_permitidas',
            field=models.ManyToManyField(blank=True, null=True, to='est.Zona'),
        ),
        migrations.AddField(
            model_name='centronegocios',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Planta'),
        ),
        migrations.AddField(
            model_name='centronegocios',
            name='zonas',
            field=models.ManyToManyField(blank=True, null=True, to='est.Zona'),
        ),
    ]
